administration/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AdministrationView.as_view(), name='index'),
    # Group URLs
    path('groups/', views.GroupsView.as_view(), name='groups'),
    path('add-group/', views.AddGroupView.as_view(), name='add-group'),
    path('edit-group/<int:pk>/', views.EditGroupView.as_view(), name='edit-group'),
    path('view-group/<int:pk>/', views.ViewGroupView.as_view(), name='view-group'),
    # User URLs
    path('add-user/', views.UserAddView.as_view(), name='add-user'),
    # ********** Fetch Requests **********
    path('fetch-ldap-users/', views.fetch_ldap_users, name='fetch-ldap-users'),
    path('check-user-exists/', views.check_user_exists, name='check-user-exists'),
    path('get-instances/', views.get_instances, name='get-instances'),
    path('change-user-membership/', views.change_user_membership, name='change-user-membership'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/', include(('administration.urls', 'administration'), namespace='administration')),
    path('', include(('tableviewer.urls', 'tableviewer'), namespace='tableviewer')),
    # third-party apps
]

tableviewer/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from core import urls
from . import views
from . import auth_views


urlpatterns = [
    path('', views.TablesListView.as_view(), name='index'),
    path('new-table/', views.AddTableView.as_view(), name='new-table'),
    path('edit-table/<int:pk>/', views.EditTableView.as_view(), name='edit-table'),
    path('tables/', views.TablesListView.as_view(), name='tables-list'),
    path('tables/detail/<int:pk>/', views.TableDetailView.as_view(), name='table-detail'),
    # ********** Table Viewing URLs **********
    path('tables/view/<int:table_id>/', views.TableView.as_view(), name='table-view'),
    # ********** Table searching URLs **********
    path('tables/search-table/<int:table_id>/', views.SearchTable.as_view(), name='search-table'),
    path('search-table/<str:shortcut>/', views.SearchTable.as_view(), name='search-table'),
    # ********** Authentication URLs **********
    path('login/', auth_views.UserLogin.as_view(), name='login'),
    path('logout/', auth_views.UserLogout.as_view(), name='logout'),
    # ********** Fetch Requests **********
    path('save-column/', views.save_column, name='save-column'),
    path('regenerate-columns/<int:table_id>/', views.regenerate_columns, name='regenerate-columns'),
    path('add-url-shortcut/<int:table_id>', views.add_url_shortcut, name='add-url-shortcut'),
    path('remove-shortcut/', views.remove_url_shortcut, name='remove-shortcut'),
    path('get-domain-name/', views.get_domain_name, name='get-domain-name'),
    path('save-table-settings/', views.save_table_settings, name='save-table-settings'),
    # Third-party URLS
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# URL shortcut URLs
urlpatterns += [
    re_path(r'^(?P<shortcut>.+)/$', views.TableView.as_view(), name='table-view'),
    re_path(r'^search-table/(?P<shortcut>.+)/$', views.SearchTable.as_view(), name='search-table'),
]

core/templates/includes/header.html
<nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;" data-bs-theme="light">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'tableviewer:index' %}">Table Viewer</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% include 'includes/links.html' %}
            </ul>
        </div>
        <div class="dropdown">
            {% if request.user.is_authenticated %}
                <a class="dropdown-toggle text-decoration-none" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{ request.user.first_name }} {{ request.user.last_name }}
                </a>
                <ul class="dropdown-menu dropdown-menu-end">
                    <li><a class="dropdown-item" href="{% url 'administration:groups' %}">My Groups</a></li>
                    <li><a class="dropdown-item" href="{% url 'tableviewer:logout' %}">Logout</a></li>
                    {% if request.user.is_superuser %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a href="{% url 'administration:index' %}" class="dropdown-item">Administration</a></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>
    </div>
</nav>

core/templates/includes/links.html
<li class="nav-item"><a class="nav-link" href="{% url 'tableviewer:tables-list' %}">Tables</a></li>
<li class="nav-item"><a class="nav-link" href="{% url 'tableviewer:new-table' %}">New Table</a></li>

core/templates/includes/shortcut.html
{% load tableviewer_extras %}
<div class="input-group mb-3">
    <span class="input-group-text">{{ domain_name }}</span>
    <p class="my-auto mx-1">/</p>
    {% for path in shortcut.url|split_path %}
        <span class="input-group-text">{{ path }}</span>
        {% if not forloop.last %}
        <p class="my-auto mx-1">/</p>
        {% endif %}
    {% endfor %}
    {# copy and delete buttons #}
    <button id="shortcut-{{ shortcut.id }}" class="copy-url-btn btn btn-outline-secondary" title="copy url" data-url-id="{{ shortcut.id }}" data-link="{{ shortcut.url|get_copy_url }}"><i class="fa-solid fa-copy"></i></button>
    <button class="delete-url-btn btn btn-outline-secondary" title="remove url" data-url-id="{{ shortcut.id }}"><i class="fa-solid fa-trash"></i></button>
</div>

core/templates/includes/top-banner.html
<div id="top-banner" class="alert alert-{{ banner.type }} position-relative top-0 start-0 w-100 mb-0 text-center" role="alert">
    <i class="{{ banner.icon }}"></i> {{ banner.message }}
</div>