administration/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.AdministrationView.as_view(), name='index'),
    # Group URLs
    path('groups/', views.GroupsView.as_view(), name='groups'),
    path('add-group/', views.AddGroupView.as_view(), name='add-group'),
    path('edit-group/<int:pk>/', views.EditGroupView.as_view(), name='edit-group'),
    path('view-group/<int:pk>/', views.ViewGroupView.as_view(), name='view-group'),
    # User URLs
    path('add-user/', views.UserAddView.as_view(), name='add-user'),
    # ********** Fetch Requests **********
    path('fetch-ldap-users/', views.fetch_ldap_users, name='fetch-ldap-users'),
    path('check-user-exists/', views.check_user_exists, name='check-user-exists'),
    path('get-instances/', views.get_instances, name='get-instances'),
    path('change-user-membership/', views.change_user_membership, name='change-user-membership'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('administration/', include(('administration.urls', 'administration'), namespace='administration')),
    path('', include(('tableviewer.urls', 'tableviewer'), namespace='tableviewer')),
    # third-party apps
]

tableviewer/urls.py
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from core import urls
from . import views
from . import auth_views


urlpatterns = [
    path('', views.TablesListView.as_view(), name='index'),
    path('new-table/', views.AddTableView.as_view(), name='new-table'),
    path('edit-table/<int:pk>/', views.EditTableView.as_view(), name='edit-table'),
    path('tables/', views.TablesListView.as_view(), name='tables-list'),
    path('tables/detail/<int:pk>/', views.TableDetailView.as_view(), name='table-detail'),
    # ********** Table Viewing URLs **********
    path('tables/view/<int:table_id>/', views.TableView.as_view(), name='table-view'),
    # ********** Table searching URLs **********
    path('tables/search-table/<int:table_id>/', views.SearchTable.as_view(), name='search-table'),
    path('search-table/<str:shortcut>/', views.SearchTable.as_view(), name='search-table'),
    # ********** Authentication URLs **********
    path('login/', auth_views.UserLogin.as_view(), name='login'),
    path('logout/', auth_views.UserLogout.as_view(), name='logout'),
    # ********** Fetch Requests **********
    path('save-column/', views.save_column, name='save-column'),
    path('regenerate-columns/<int:table_id>/', views.regenerate_columns, name='regenerate-columns'),
    path('add-url-shortcut/<int:table_id>', views.add_url_shortcut, name='add-url-shortcut'),
    path('remove-shortcut/', views.remove_url_shortcut, name='remove-shortcut'),
    path('get-domain-name/', views.get_domain_name, name='get-domain-name'),
    path('save-table-settings/', views.save_table_settings, name='save-table-settings'),
    # Third-party URLS
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# URL shortcut URLs
urlpatterns += [
    re_path(r'^(?P<shortcut>.+)/$', views.TableView.as_view(), name='table-view'),
    re_path(r'^search-table/(?P<shortcut>.+)/$', views.SearchTable.as_view(), name='search-table'),
]

administration/models.py
from django.db import models
from django.contrib.auth.models import User


class SiteGroup(models.Model):
    name = models.CharField(max_length=100)
    department = models.CharField(max_length=100, blank=True, null=True)
    members = models.ManyToManyField(User, blank=True, related_name='group_memberships')
    owners = models.ManyToManyField(User, blank=True, related_name='group_ownerships')
    tables = models.ManyToManyField('tableviewer.DynamicTable', blank=True, related_name='group_tables')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Site Group'
        verbose_name_plural = 'Site Groups'
        ordering = ['name']

administration/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import SiteGroup


class SiteGroupForm(forms.ModelForm):
    class Meta:
        model = SiteGroup
        fields = ['name', 'department']
        exclude = ['owners', 'members']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'department': forms.TextInput(attrs={'class': 'form-control'}),
        }


class AddUserForm(ModelForm):
    search_user = forms.CharField(widget=forms.TextInput(attrs={
        "class": "form-control auto-input", "autofocus": True, 'required': True, 'autocomplete': 'off',
        'data-user-selected': 'false'
    }))

    class Meta:
        model = User
        fields = ('search_user', 'username', 'first_name', 'last_name', 'email')
        widgets = {
            'username': forms.TextInput(attrs={"class": "form-control readonly", "readonly": True}),
            'first_name': forms.TextInput(attrs={"class": "form-control readonly", "readonly": True}),
            'last_name': forms.TextInput(attrs={"class": "form-control readonly", "readonly": True}),
            'email': forms.TextInput(attrs={"class": "form-control readonly", "readonly": True}),
        }

administration/views.py
import json

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, CreateView
from django.core.exceptions import ObjectDoesNotExist

from .models import SiteGroup
from tableviewer.models import DynamicTable
from .utils import *
from .forms import SiteGroupForm, AddUserForm


class GroupsView(LoginRequiredMixin, View):
    title = "My Groups"
    template_name = 'administration/groups/groups.html'

    def get(self, request, *args, **kwargs):
        user_groups = SiteGroup.objects.filter(owners=request.user)
        context = {
            'title': self.title,
            'user_groups': user_groups
        }
        return render(request, self.template_name, context)


class AddGroupView(LoginRequiredMixin, View):
    title = "Add Group"
    template_name = 'administration/groups/add_group.html'
    action = "add"

    def get(self, request, *args, **kwargs):
        form = SiteGroupForm()
        context = {
            'title': self.title,
            'form': form,
            'action': self.action,
        }
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = SiteGroupForm(request.POST)
        if form.is_valid():
            group = form.save()

            # Add the user to members
            group.members.add(request.user)

            # Optionally, add the user to owners too
            group.owners.add(request.user)

            return redirect(reverse_lazy('administration:groups'))
        else:
            context = {
                'title': self.title,
                'form': form,
            }
            return render(request, self.template_name, context)


class EditGroupView(LoginRequiredMixin, View):
    title = "Edit Group"
    template_name = 'administration/groups/add_group.html'
    success_template_name = 'administration/view_group.html'
    action = "edit"

    def get(self, request, pk, *args, **kwargs):
        instance = SiteGroup.objects.get(pk=pk)
        form = SiteGroupForm(instance=instance)
        context = {
            'title': self.title,
            'form': form,
            'action': self.action,
            'instance': instance,
        }
        return render(request, self.template_name, context)

    def post(self, request, pk, *args, **kwargs):
        instance = SiteGroup.objects.get(pk=pk)
        form = SiteGroupForm(request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect(reverse_lazy('administration:view-group', kwargs={'pk': pk}))
        else:
            context = {
                'title': self.title,
                'form': form,
                'action': self.action,
                'instance': SiteGroup.objects.get(pk=pk),
            }
            return render(request, self.template_name, context)


class ViewGroupView(LoginRequiredMixin, View):
    title = ""
    template_name = 'administration/groups/view_group.html'

    def get(self, request, pk, *args, **kwargs):
        group = SiteGroup.objects.get(pk=pk)
        self.title = group.name
        context = {
            'title': self.title,
            'group': group
        }
        return render(request, self.template_name, context)


class AdministrationView(View):
    title = "Administration"
    template_name = 'administration/administration.html'

    def get(self, request, *args, **kwargs):
        groups = SiteGroup.objects.all()
        users = User.objects.all()
        tables = DynamicTable.objects.all()

        context = {
            'title': self.title,
            'groups': groups,
            'users': users,
            'tables': tables,
        }
        return render(request, self.template_name, context)


class UserAddView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('user-login')
    model = User
    form_class = AddUserForm
    template_name = 'administration/users/add_user.html'
    success_url = reverse_lazy('users-list')

    def get_context_data(self, **kwargs):
        context = super(UserAddView, self).get_context_data(**kwargs)
        context['title'] = 'Add User'
        context['action'] = 'Add'
        # context['cancel_url'] = self.request.META.get('HTTP_REFERER')
        # support form data
        # user = self.request.user
        # if user.is_anonymous:
        #     context['support_form'] = SupportForm(initial={'url': self.request.path})
        # else:
        #     context['support_form'] = SupportForm(initial={
        #         'name': f'{user.first_name} {user.last_name}',
        #         'email': user.email,
        #         'url': self.request.path,
        #     })
        return context

    # setting unusable password for added users
    def form_valid(self, form):
        # create the new user
        user = create_user(form)
        messages.success(self.request, 'User created!')
        return redirect(reverse_lazy('administration:index'))


# ## Group Fetch Calls ##
def add_user_to_group(request):
    search_by = request.GET.get('search_by', None)
    if search_by:
        pass


# ##### Fetch calls related to retrieving users #####
def change_user_membership(request):
    user_pk = request.GET.get('user_id', None)  # getting the pk from the payload
    group_pk = request.GET.get('group_id', None)  # retrieving the group's pk from payload
    change_type = request.GET.get('change_type', None)  # add or remove
    membership = request.GET.get('membership', None)  # owner or member
    full_remove = request.GET.get('full_remove')  # when removing user as owner, if they would like to remove them as member too
    user_data = {
        "user_id": user_pk,
        "group_id": group_pk,
        "change_type": change_type,
        "membership": membership,
        "full_remove": full_remove == 'True'
    }
    try:
        # making sure the pk is present
        if user_pk is None or group_pk is None:
            raise ValueError("Owner or Member pk is none")

        user = User.objects.get(pk=user_pk)  # getting the user instance
        group = SiteGroup.objects.get(pk=group_pk)  # getting the SiteGroup instance

        try:
            # applying the requested change
            change_member_membership(user, group, change_type=change_type, membership=membership)
            # creating a dictionary of the user instance
            user_dict = user.__dict__
            user_dict.pop('_state')  # removing state because what the hell even is that
            user_dict.pop('password')  # removing the password for obvious reasons.

            context = {
                "success": True,
                "user": user_dict,
                "user_data": user_data
            }
            return JsonResponse(context, safe=False)
        except ValueError as e:
            raise ValueError(e)
    except ValueError as e:
        return JsonResponse({'error': str(e), 'status': "error", 'user_data': user_data})
    except User.DoesNotExist or SiteGroup.DoesNotExist as e:
        return JsonResponse({'error': str(e), 'status': "error"})


# ## LDAP Fetch Calls ##
def fetch_ldap_users(request):
    ldapi = Ldap()
    query_param = request.GET.get("q")
    if query_param is not None or query_param != "":
        user_data = ldapi.get_users(query_param)
        if user_data[0]:
            return JsonResponse(user_data[1], safe=False)

    return JsonResponse({"q": query_param}, safe=False)


def check_user_exists(request):
    # loading the payload body property as a dictionary
    user_data = json.loads(request.body)
    filter_by = user_data.get('filter_by', None)
    # searching the database for the user by username
    user_instance = User.objects.filter(**filter_by).first()

    if user_instance:
        user_dict = user_instance.__dict__
        user_dict.pop('_state')
        user_dict.pop('password')
        return JsonResponse({'exists': True, 'user': user_dict}, safe=True)
    else:
        return JsonResponse({'exists': False})


def check_user_valid(request):
    ldapi = Ldap()
    user = request.GET.get("user")
    user_exists_in_ad = True if ldapi.check_user_exists(user, "mail")[0] is not False else False
    if user_exists_in_ad:
        return JsonResponse(json.dumps({"exists": True}), safe=False)
    else:
        return JsonResponse(json.dumps({
            "exists": False,
            "message": "User does not exist in the organization."
        }), safe=False)


def get_instances(request):
    model_type = request.GET.get("type", None)
    col_filter = request.GET.get("filter", None)
    q = request.GET.get("q", None)
    if model_type is not None and q is not None and col_filter is not None:
        filter_by = {
            f"{col_filter}__icontains": q,
        }
        model = get_objects_by_type(model_type)
        if "_name" in col_filter:
            object_instances = model.objects.filter(**filter_by).values_list("pk", "first_name", "last_name")
            instances_serialized = json.dumps([
                {"id": instance[0], "firstName": instance[1], "lastName": instance[2]}
                for instance in object_instances
            ])
        else:
            object_instances = model.objects.filter(**filter_by).values_list("pk", "name")
            instances_serialized = json.dumps([
                {"id": instance[0], "name": instance[1]}
                for instance in object_instances
            ])
        return JsonResponse(instances_serialized, safe=False)
    else:
        return JsonResponse({"message": "Please provide query parameters"}, safe=False)

administration/templates/administration/administration.html
{% extends 'base.html' %}
{% load administration_extras %}

{% block content %}
    <h3 class="border-bottom mb-3">Administration</h3>

    <div class="mb-5">
        <p>Administer users and groups here. Choose a tab for the relevant list to view or edit.</p>
    </div>

    <div id="tabs">
        {# tab nav-links #}
        <ul class="nav nav-tabs mb-3">
            <li class="nav-item">
                <a id="tabBtn1" role="button" class="tab-btn nav-link active" aria-current="true" data-target="tab1">Users</a>
            </li>
            <li class="nav-item">
                <a id="tabBtn2" role="button" class="tab-btn nav-link" aria-current="false" data-target="tab2">Groups</a>
            </li>
            <li class="nav-item">
                <a id="tabBtn3" role="button" class="tab-btn nav-link" aria-current="false" data-target="tab3">Tables</a>
            </li>
        </ul>

        {# tab contents #}
        {# tab 1 content #}
        <div id="tab1" class="tab-content" data-hidden="false">
            <div class="mb-3 border-bottom d-flex justify-content-between align-items-center">
                <h3 class="mb-0">Users</h3>
                <a href="{% url 'administration:add-user' %}">Add User</a>
            </div>
            <table id="membersTable" class="table table-bordered table-striped">
                <thead class="table-primary">
                    <tr>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Groups</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.first_name }}</td>
                        <td>{{ user.last_name }}</td>
                        <td>{{ user.group_memberships.all|format_list:"name" }}</td>
                        <td><a href="#view-user">View</a> | <a href="#edit-user">Edit</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {# tab 2 content #}
        <div id="tab2" class="tab-content hidden" data-hidden="true">
            <div class="mb-3 border-bottom d-flex justify-content-between align-items-center">
                <h3 class="mb-0">Groups</h3>
                <a class="link-primary" href="{% url 'administration:add-group' %}">Add new group</a>
            </div>
            <table id="ownersTable" class="table table-bordered table-striped">
                <thead class="table-primary">
                    <tr>
                        <th>Group Name</th>
                        <th>Department</th>
                        <th>Members</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for group in groups %}
                    <tr>
                        <td>{{ group.name }}</td>
                        <td>{{ group.department }}</td>
                        <td>{{ group.members.all|format_list:"username" }}</td>
                        <td><a href="{% url 'administration:view-group' pk=group.pk %}">View</a> | <a href="{% url 'administration:edit-group' pk=group.pk %}">Edit</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        {# tab 3 content #}
        <div id="tab3" class="tab-content hidden" data-hidden="true">
            <div class="mb-3 border-bottom d-flex justify-content-between align-items-center">
                <h3 class="mb-0">Tables</h3>
                <a href="{% url 'tableviewer:new-table' %}">Add new table</a>
            </div>
            <table id="tablesTable" class="table table-bordered table-striped">
                <thead class="table-primary">
                    <tr>
                        <th>Table Name</th>
                        <th>Department</th>
                        <th>Member Of</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for table in tables %}
                    <tr>
                        <td>{{ table.name }}</td>
                        <td>{{ table.description }}</td>
                        <td>{{ table.group_tables.all|format_list:"name" }}</td>
                        <td><a href="{% url 'tableviewer:table-detail' pk=table.pk %}">View</a> | <a href="{% url 'tableviewer:edit-table' pk=table.pk %}">Edit</a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}